gpu: 6
num_iterative_stage: 3
sample_save_path: ./test_samples
model_path: ./checkpoints/model_49_1.pth

dataset: SCUT-enstext
data:
  test_data_root: /home/byeongkyu/vampsabbath
  input_size: [1024, 1024]
  batch_size: 1
