gpu: 0
num_iterative_stage: 3

path:
  root: ./results/scut/1019_0
  model_save_path: ./results/scut/1019_0/checkpoints
  sample_save_path: ./results/scut/1019_0/samples
  tensorboard_path: ./results/scut/1019_0/tensorboard

epoch: 200
sample_interval: 50
model_save_interval: 1000

data:
  name: scut
  train_data_root: /data2/data/SCUT-enstext/train
  no_text_sample_rate: 0
  input_size: [512, 512]
  batch_size: 8

optimizer:
  lr: 0.0001
  beta1: 0.5
  beta2: 0.9

loss_weight:
  dice_weight: 3
  gs_weight: 200
  neg_ssim_weight: 1
  rs_weight: 2
  tv_weight: 0
  vgg_weight: 1
dice_loss_param:
  smooth: 1.0
gs_loss_param:
  kernel_sizes: [1, 4, 8]
neg_ssim_loss_param:
  window_size: 11
rs_loss_param:
  lambda_out: 13
  lambda_p1: 10
  lambda_p2: 12
  beta_out: 2
  beta_p1: 0.8
  beta_p2: 1
